class Position:
    def __init__(self, responseJSON):
        # parsed_json = json.loads(responseJSON)
        self.status = responseJSON.get('status')
        self.message = responseJSON.get('message')
        self.errorcode = responseJSON.get('errorcode')
        self.data = []
        if responseJSON.get('data'):
            for position in responseJSON.get('data'):
                self.data.append(Data(position))

class Data:
    def __init__(self, json):
        # parsed_json = json.loads(json)
        self.exchange = json.get('exchange')
        self.symboltoken = json.get('symboltoken')
        self.producttype = json.get('producttype')
        self.tradingsymbol = json.get('tradingsymbol')
        self.symbolname = json.get('symbolname')
        self.instrumenttype = json.get('instrumenttype')
        self.priceden = json.get('priceden')
        self.pricenum = json.get('pricenum')
        self.genden = json.get('genden')
        self.gennum = json.get('gennum')
        self.precision = json.get('precision')
        self.multiplier = json.get('multiplier')
        self.boardlotsize = json.get('boardlotsize')
        self.buyqty = int(json.get('buyqty'))
        self.sellqty = json.get('sellqty')
        self.buyamount = json.get('buyamount')
        self.sellamount = json.get('sellamount')
        self.symbolgroup = json.get('symbolgroup')
        self.strikeprice = json.get('strikeprice')
        self.optiontype = json.get('optiontype')
        self.expirydate = json.get('expirydate')
        self.lotsize = json.get('lotsize')
        self.cfbuyqty = json.get('cfbuyqty')
        self.cfsellqty = json.get('cfsellqty')
        self.cfbuyamount = json.get('cfbuyamount')
        self.cfsellamount = json.get('cfsellamount')
        self.buyavgprice = json.get('buyavgprice')
        self.sellavgprice = json.get('sellavgprice')
        self.avgnetprice = json.get('avgnetprice')
        self.netvalue = json.get('netvalue')
        self.netqty = int(json.get('netqty'))
        self.totalbuyvalue = json.get('totalbuyvalue')
        self.totalsellvalue = json.get('totalsellvalue')
        self.cfbuyavgprice = json.get('cfbuyavgprice')
        self.cfsellavgprice = json.get('cfsellavgprice')
        self.totalbuyavgprice = json.get('totalbuyavgprice')
        self.totalsellavgprice = json.get('totalsellavgprice')
        self.netprice = json.get('netprice')
        self.ltp = json.get('ltp')

